apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  labels:
    app: nginxapp
spec:
  containers:
    - name: nginxapp
      image: jfogue/nginxapp:0fb9bd72df05eb5bcf75949f4a44b18b8bec31fc
      ports:
        - containerPort: 8080
