---
- name: Download eksctl, and add it to the path
  block:
    - name: Installing eksctl
      shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      args:
        warn: no
    - name: Move the extracted binary to /usr/local/bin  
      shell: mv /tmp/eksctl /usr/local/bin
      become: yes
    - name: check eksctl version
      shell: eksctl version